apiVersion: 1

datasources:
  - name: Tempo-Dev
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo-dev
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki-dev
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus-dev
      nodeGraph:
        enabled: true

  - name: Prometheus-Dev
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus-dev
    isDefault: true

  - name: Loki-Dev
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-dev
